name: Poll JSM tickets & flatten details

# grant contents write so commits & pushes succeed
permissions:
  contents: write

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  poll-and-flatten:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # persist the GITHUB_TOKEN so we can push back
          persist-credentials: true

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests python-dotenv

      - name: Prepare artifacts & memory
        run: |
          mkdir -p artifacts
          touch .processed_issues

      - name: Run Jira polling script
        env:
          JIRA_EMAIL:   ${{ secrets.JIRA_EMAIL }}
          JIRA_TOKEN:   ${{ secrets.JIRA_TOKEN }}
          JIRA_PROJECT: ${{ vars.JIRA_PROJECT }}
          JIRA_STATUS:  ${{ vars.JIRA_STATUS }}
          JIRA_SITE:    ${{ vars.JIRA_SITE }}
        run: python jira/jira_polling_script.py

      - name: Commit & push memory update
        if: success()
        run: |
          git config user.name  "GitHub Actions"
          git config user.email "actions@github.com"
          git add .processed_issues
          git commit -m "chore: update processed issues [skip ci]" || echo "Nothing to commit"
          git push