---
# This playbook is used to configure a Palo Alto Networks firewall by creating an address object, 
# adding a NAT rule, and committing the configuration. It uses the Palo Alto Networks Ansible 
# collection to interact with the firewall.

# Tasks:
# 1. Gather system info:
#    - Specifies the target host as "firewall" and uses local connection.
#    - Loads variables from external files: `vars/palo-secrets.yml` and `vars/input-variables.yml`.
#    - Defines the `device` variable containing firewall connection details.

# 2. Create source address object:
#    - Creates an address object on the firewall with the specified name, IP address, and description.
#    - Ensures the object is in the "present" state.

# 3. Add NAT rule for inbound web server:
#    - Configures a NAT rule to forward HTTP traffic from an external address to an internal web server.
#    - Uses the previously created address object as the destination address.
#    - Sets the NAT rule to use dynamic translation with round-robin distribution.

# 4. Commit configuration:
#    - Commits the configuration changes to the firewall.
#    - Registers the commit results for further use.

# 5. Display commit message:
#    - Outputs the commit job ID and details for verification.

# Documentation:
# https://pan.dev/ansible/docs/panos/
# https://galaxy.ansible.com/ui/repo/published/paloaltonetworks/panos/docs/
- name: Gather system info
  hosts: all
  connection: local
  # vars_files:
  #   - vars/input-variables.yml
  vars:
    device:
      ip_address: "{{ ansible_host }}"
      # username: "{{ lookup('env','PANOS_USER') }}"
      # password: "{{ lookup('env','PANOS_PASSWORD') }}"
      username: "{{ lookup('env','PALO_ADMIN_USER') }}"
      password: "{{ lookup('env','PALO_ADMIN_PW') }}"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Load ticket JSON into var 'ticket'
      include_vars:
        file: "{{ lookup('env','ARTIFACT') }}"
        name: ticket
    # sample json from a previous ticket
    # "ticket": {
    #     "Business Justification": "cause i said so",
    #     "Destination IP": "4.3.2.1",
    #     "Destination Port": "80",
    #     "Protocol": "TCP",
    #     "Source IP Address": "1.2.3.4",
    #     "created": "2025-04-28T19:44:35.859+0000",
    #     "description": "",
    #     "formId": "8c3def98-b678-43d7-8df8-ebe5bfb46e8f",
    #     "formName": "Firewall Request",
    #     "issueKey": "JTEJ-3",
    #     "status": "Ready For Production",
    #     "summary": "this is a test ticket to create a firewall rule",
    #     "updated": "2025-05-08T22:10:38.582+0000"
    # }
    - name: Extract JSON fields into friendly vars
      set_fact:
        business_justification: "{{ ticket['Business Justification'] }}"
        destination_ip:         "{{ ticket['Destination IP'] }}"
        destination_port:       "{{ ticket['Destination Port'] | int }}"
        protocol:               "{{ ticket['Protocol'] }}"
        source_ip_address:      "{{ ticket['Source IP Address'] }}"
        created:                "{{ ticket['created'] }}"
        description:            "{{ ticket['description'] }}"
        form_id:                "{{ ticket['formId'] }}"
        form_name:              "{{ ticket['formName'] }}"
        issue_key:              "{{ ticket['issueKey'] }}"
        status:                 "{{ ticket['status'] }}"
        summary:                "{{ ticket['summary'] }}"
        updated:                "{{ ticket['updated'] }}"
    
    # Previously used variables here for reference only
    # object_name: "web-server-internal-ip"
    # object_ip: "172.16.2.15/32"
    # object_description: "Web server internal IP address"
    # rule_name: "inbound-web-server-1"
    # rule_description: "Inbound web server rule"
    - name: Debug mixed test output
      debug:
        msg:
          - "Address Obect Name: {{ issue_key }}-{{destination_ip}}"
          - "NAT Rule Name: {{ issue_key }}-{{destination_ip}}"
          - "Hostname: {{ inventory_hostname }}"
          - "Device IP: {{ ansible_host }}"
          - "Business Justification: {{ business_justification }}"
          - "Destination IP: {{ destination_ip }}"
          - "Issue Key: {{ issue_key }}"
          - "Summary: {{ summary }}"

    - name: Create source address object
      paloaltonetworks.panos.panos_address_object:
        provider: "{{ device }}"
        name: "{{ issue_key }}-{{ destination_ip | replace('/', '-') }}"
        address_type: "ip-netmask"
        value: "{{ destination_ip }}"
        description: "{{ description }}"
        state: "present"

    - name: Add NAT rule for inbound web server
      paloaltonetworks.panos.panos_nat_rule2:
        provider: '{{ device }}'
        name: "{{ issue_key }}-{{ destination_ip | replace('/', '-') }}"
        description: "{{ summary }}"
        nat_type: 'ipv4'
        from_zones:
          - 'outside'
        to_zones:
          - 'outside'
        to_interface: 'ethernet1/1'
        service: 'any'
        source_addresses:
          - 'any'
        destination_addresses:
          - '172.16.1.166'
        destination_translated_address: 'web-server-internal-ip'
        state: 'present'


    - name: Commit configuration
      paloaltonetworks.panos.panos_commit_firewall:
        provider: "{{ device }}"
      register: results
    
    - name: Dispaly commit message
      debug:
        msg: "Commit with Job ID: {{ results.jobid }} had output: {{ results.details }}"