version: '3.8'

services:
  nautobot:
    image: networktocode/nautobot-lab
    container_name: nautobot
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - /home/ubuntu/chi-nog-12/docker/nautobot/plugins:/opt/nautobot/plugins:rw