version: '3'
services:
  nautobot:
    image: ghcr.io/nautobot/nautobot:latest
    ports:
      - "8000:8080"
    environment:
      - SUPERUSER_NAME=admin
      - SUPERUSER_EMAIL=admin@example.com
      - SUPERUSER_PASSWORD=admin
      - NAUTOBOT_DB_HOST=db
      - NAUTOBOT_DB_NAME=nautobot
      - NAUTOBOT_DB_USER=nautobot
      - NAUTOBOT_DB_PASSWORD=nautobot
      - NAUTOBOT_REDIS_HOST=redis
    depends_on:
      - db
      - redis
    volumes:
      - nautobot_data:/opt/nautobot

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=nautobot
      - POSTGRES_USER=nautobot
      - POSTGRES_PASSWORD=nautobot
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: unless-stopped

volumes:
  nautobot_data:
  pg_data: