---
- name: Hello World — dump all ticket JSON vars
  hosts: all
  gather_facts: false

  tasks:
    - name: Load ticket JSON into var 'ticket'
      include_vars:
        file: "{{ lookup('env','ARTIFACT') }}"
        name: ticket

    - name: Show me everything in the ticket JSON
      debug:
        var: ticket